
name: "Bump Version"

on:
  push:
    branches: [ qa, master]

jobs:
  bump-version:
    name: "Bump Version"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name:  'Automated Version Bump for qa'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  'add, Adds'
          major-wording:  'MAJOR,cut-major'
          target-branch: 'qa'   
          rc-wording:     'RELEASE, alpha'
          skip-tag:  'true'    
      - name: package-version-for-tag-to-master
        if: github.ref == 'refs/heads/master'
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: package-version-to-git-tag--info
        if: github.ref == 'refs/heads/master'
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"  
      - name: "cat package.json"
        run: cat ./package.json
      - name:  'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
